
m fastapi import FastAPI, Form, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field, field_validator
from typing import Optional, List
import io
import json
import hashlib
import re
from pathlib import Path
from rdkit import Chem
from rdkit.Chem import Draw
import pubchempy as pubpy

BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "images"
OUTPUT_DIR.mkdir(exist_ok=True)
ITEMS_PATH = BASE_DIR / "items.json"
SIZE = (200, 200)


class InputValid(BaseModel):
        smi_in: str = Field(..., min_length=1)

            @field_validator("smi_in")
                @classmethod
                    def veri_smi(cls, v: str) -> str:
                                v = v.strip()
                                        if not v:
                                                        raise TypeError("SMILES are of type str, not None")
                                                            smi_2_mol = Chem.MolFromSmiles(v)
                                                                    if smi_2_mol is not None:
                                                                                    return Chem.MolToSmiles(smi_2_mol)
                                                                                        raise ValueError(f"Invalid SMILES string: {v}")


                                                                                    class MolData:
                                                                                            def __init__(self) -> None:
                                                                                                        self.mol_data: List[dict] = []

                                                                                                            def img_2_bytes(self, smi_in: str) -> bytes:
                                                                                                                        mol_obj = Chem.MolFromSmiles(smi_in)
                                                                                                                                if mol_obj is None:
                                                                                                                                                raise ValueError(f"Failed to parse SMILES: {smi_in}")
                                                                                                                                                    try:
                                                                                                                                                                    mol_img = Draw.MolToImage(mol_obj, size=(100, 100))
                                                                                                                                                                                img_bytes = io.BytesIO()
                                                                                                                                                                                            mol_img.save(img_bytes, format="PNG")
                                                                                                                                                                                                        img_bytes.seek(0)
                                                                                                                                                                                                                    return img_bytes.getvalue()
                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                        raise RuntimeError(f"General Error: {e}")

                                                                                                                                                                                                                                        def get_iupac(self, smi_in: str) -> Optional[str]:
                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                    smi_iupac = pubpy.get_compounds(smi_in, "smiles")
                                                                                                                                                                                                                                                                                return smi_iupac[0].iupac_name
                                                                                                                                                                                                                                                                                    except Exception:
                                                                                                                                                                                                                                                                                                    return None

                                                                                                                                                                                                                                                                                                    def append_mol_data(self, smi_in: str) -> dict:
                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                col_iupac = self.get_iupac(smi_in)
                                                                                                                                                                                                                                                                                                                                            col_img_bytes = self.img_2_bytes(smi_in)
                                                                                                                                                                                                                                                                                                                                                        dict_mol_data = {
                                                                                                                                                                                                                                                                                                                                                                                "smi_in": smi_in,
                                                                                                                                                                                                                                                                                                                                                                                                "iupac": col_iupac or "Unk",
                                                                                                                                                                                                                                                                                                                                                                                                                "img_bytes": col_img_bytes or b"",
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                    self.mol_data.append(dict_mol_data)
                                                                                                                                                                                                                                                                                                                                                                                return dict_mol_data
                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                    raise RuntimeError(f"Error in append_mol_data: {e}")

                                                                                                                                                                                                                                                                                                                                                                                                    def clear_mol_data(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                self.mol_data = []


                                                                                                                                                                                                                                                                                                                                                                                                                class SubstMatch:
                                                                                                                                                                                                                                                                                                                                                                                                                        sub_mol_pfeca = Chem.MolFromSmarts("[O]C(C(O)=O)F")
                                                                                                                                                                                                                                                                                                                                                                                                                            sub_mol_pfsa = Chem.MolFromSmarts("O=[S](O)=O")
                                                                                                                                                                                                                                                                                                                                                                                                                                sub_mol_ftoh = Chem.MolFromSmarts("OC[CH2]")
                                                                                                                                                                                                                                                                                                                                                                                                                                    sub_mol_mefasaa = Chem.MolFromSmarts("CN(CC(O)=O)[S](=O)=O")
                                                                                                                                                                                                                                                                                                                                                                                                                                        sub_mol_ftca = Chem.MolFromSmarts("[CH2]CC(O)=O")
                                                                                                                                                                                                                                                                                                                                                                                                                                            sub_mol_fts = Chem.MolFromSmarts("[CH2]CS(=O)(O)=O")
                                                                                                                                                                                                                                                                                                                                                                                                                                                sub_mol_pfca = Chem.MolFromSmarts("O=[C]O")
                                                                                                                                                                                                                                                                                                                                                                                                                                                    sub_mol_fasa = Chem.MolFromSmarts("N[S](=O)=O")

                                                                                                                                                                                                                                                                                                                                                                                                                                                        def __init__(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.pfeca: List[tuple] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.fasa: List[tuple] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.pfca: List[tuple] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.fts: List[tuple] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.ftca: List[tuple] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.mefasaa: List[tuple] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.ftoh: List[tuple] = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.pfsa: List[tuple] = []

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def match_pfeca(self, mol_in) -> bool:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if mol_in and mol_in.HasSubstructMatch(self.sub_mol_pfeca):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            matched_smiles = Chem.MolToSmiles(mol_in)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.pfeca.append((matched_smiles, mol_in))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return False

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def match_fasa(self, mol_in) -> bool:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if mol_in and mol_in.HasSubstructMatch(self.sub_mol_fasa):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    matched_smiles = Chem.MolToSmiles(mol_in)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.fasa.append((matched_smiles, mol_in))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return False

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def match_pfca(self, mol_in) -> bool:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if mol_in and mol_in.HasSubstructMatch(self.sub_mol_pfca):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            matched_smiles = Chem.MolToSmiles(mol_in)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.pfca.append((matched_smiles, mol_in))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return False

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def match_fts(self, mol_in) -> bool:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if mol_in and mol_in.HasSubstructMatch(self.sub_mol_fts):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    matched_smiles = Chem.MolToSmiles(mol_in)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.fts.append((matched_smiles, mol_in))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return False

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def match_ftca(self, mol_in) -> bool:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if mol_in and mol_in.HasSubstructMatch(self.sub_mol_ftca):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            matched_smiles = Chem.MolToSmiles(mol_in)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.ftca.append((matched_smiles, mol_in))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return False

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def match_mefasaa(self, mol_in) -> bool:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if mol_in and mol_in.HasSubstructMatch(self.sub_mol_mefasaa):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    matched_smiles = Chem.MolToSmiles(mol_in)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.mefasaa.append((matched_smiles, mol_in))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return True

